# Site settings
title: Information Assurance Student Group  
email: iasg-cabinet@iastate.edu
description: > # this means to ignore newlines until "baseurl:"
    The Information Assurance Student Group (IASG) at Iowa State University is dedicated to
    information security and holds weekly meetings for students interested in the
    InfoSec field. This semester we are meeting in Coover 1016 @ 6 - 7:00pm on Thursday.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://iasg.iac.iastate.edu" # the base hostname & protocol for your site
twitter_username: 
github_username: IASG
facebook_page: infasgroup
youtube_channel: UC-rLOtGfHGx9N1mlNNEwJNQ
slack_workspace: iasg
theme: jekyll-theme-hacker

# Build settings
markdown: kramdown

exclude: [vendor]
